### ISSUE TITLE
Update clang from 6 to 10

### ISSUE THREAD

**Issue by kuang-da** [CIS548/vagrant-env#2]
The clang in vagrant is a bit out-of-date. We are using clang 6 in VM, and the auto-grader is using clang 10. In general, there is no issue since the compiler is back-compatible. We have updated the clang in [Docker env](https://github.com/CIS548/docker-env/blob/master/docker-setup.sh). Let's do that for Vagrant as well.

I think the following 4 lines of code will do the magic.

```
apt-get install -y clang-10
apt-get install -y clang-format-10

update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100
update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-10 100
```

To make sure the updated VM works, please use it to compile your project 1 and 2.

**Comment by angelapwen** [comment]
Logistically, whoever takes this should:
- update the Vagrantfile in the Coursera backend under the Resources tab to the new version
- make sure to draft up a Piazza announcement to alert students of the change so they can replace the Vagrantfile prior to Project 1 (and run `vagrant destroy` then `vagrant up` and `clang --version` inside the VM to confirm). Ideally step by step instructions 😸

**Comment by alesparza** [comment]
there is an active pull request for this change

**Comment by alesparza** [comment]
We have a Piazza post [@16](https://piazza.com/class/krtmu8tans12en?cid=16) for #1 so we can tack on instructions to update everyone's VM to that post.  Anyone that has already started will need to `vagrant destroy`, and `vagrant up` from scratch.  ssh keys will need to be setup again as well.
