### ISSUE TITLE
[Discussion] Add ohmyzsh to VM environment?

### ISSUE THREAD

**Issue by angelapwen** [CIS548/vagrant-env#6]
I ❤️ [ohmyzsh](https://ohmyz.sh/) and I think it would make students less afraid/displeased with using the terminal on the VM if they are able to see its colors and other features. It is also really helpful for git.

A downside could be that we are not showing students the barebones view of command line/terminal. I'm not sure that is a big problem though. What do you all think?

If we install it in the VM then we also need to make sure to run the scripts to make it the default shell (and replicate into Dockerfile?)

**Comment by alesparza** [comment]
I've got colours in my shell.  Does it depend on the terminal that's used to ssh into the VM?  

This is mingw-64 that comes with git
![image](https://user-images.githubusercontent.com/55060175/131587792-00704b06-0445-4959-813e-29b9f0290c89.png)

Syntax highlighting works in vim too
![image](https://user-images.githubusercontent.com/55060175/131588037-eabfece7-0420-4aec-a30e-3228ef637430.png)

This is Windows command prompt
![image](https://user-images.githubusercontent.com/55060175/131588266-3151ea9c-e4d9-46ef-9c4f-a08a655f01b0.png)

![image](https://user-images.githubusercontent.com/55060175/131588239-0afa86d4-ac0e-4e62-b073-8d2ac81b2d30.png)

**Comment by angelapwen** [comment]
Hm I think you're right @alesparza , I am a little confused about why I've seen some students screenshare with bare-bones terminals. @kuang-da are there other reasons you like to use ohmyzsh other than the colors that you think might be useful for students? If not we can close this out.

**Comment by kuang-da** [comment]
I am not a fan of [colorful terminals](https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#the-themes) so I only use `robbyrussell` as my ohmyzsh theme.

I said ohmyzsh is convenient for Git is because it has many build in alias, which is quite handy. For instance,

```
gst: git status
gaa : git add –all
gcam: git commit -a -m
ggp: git push origin $(current_branch)
```

Also, most of time you could skip typing `cd` while changing directories. `..` is `cd ..`. Typing directory name is sufficient to get into the directory.

Moreover, ohmyzsh has a great fuzzy auto-completion.

**Comment by kuang-da** [comment]
Those thing are helpful and make it more efficient when you wrangling in the terminal. But I feel like it might be overwhelming to students who just start using terminal. 👀

**Comment by kuang-da** [comment]
One example on my terminal

![image](https://user-images.githubusercontent.com/18092300/131598776-b0c21f09-a49e-4488-a6e9-f5cf47b0b16c.png)

**Comment by angelapwen** [comment]
Oh yeah, I don't think new students need that. maybe it would be good for them to learn what the full git commands and how to use the full path for `cd`. I will close this then!!
